apiVersion: apps/v1
kind: Deployment
metadata:
  name: cm-backend
  namespace: prd-cm
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: cm-backend
  template:
    metadata:
      labels:
        app: cm-backend
    spec:
      containers:
        - name: backend-cm
          image: ghcr.io/kirapixel/flask-cm-spectr:no-ui_20260405125351
          ports:
            - containerPort: 31500
          envFrom:
            - secretRef:
                name: flask-cm-spectr-secret
