apiVersion: v1
kind: Service
metadata:
  name: cm-backend-service
  namespace: prd-cm
spec:
  selector:
    app: cm-backend
  ports:
    - protocol: TCP
      port: 31801
      targetPort: 31500
      nodePort: 31801
  type: NodePort
