apiVersion: apps/v1
kind: Deployment
metadata:
  name: cm-frontend-react
  namespace: prd-cm
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: cm-frontend-react
  template:
    metadata:
      labels:
        app: cm-frontend-react
    spec:
      containers:
        - name: cm-frontend-react
          image: ghcr.io/kirapixel/cm-frontend-react:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 80
          envFrom:
            - configMapRef:
                name: cm-frontend-react-config
            - secretRef:
                name: cm-frontend-react-secret
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 3
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 10
            periodSeconds: 15
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 300m
              memory: 256Mi
