apiVersion: v1
kind: Service
metadata:
  name: cm-frontend-react-service
  namespace: prd-cm
spec:
  selector:
    app: cm-frontend-react
  ports:
    - protocol: TCP
      port: 31802
      targetPort: 80
      nodePort: 31802
  type: NodePort
