apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fluent-bit
  namespace: argocd
spec:
  destination:
    namespace: logging
    server: https://kubernetes.default.svc
  source:
    path: logging
    repoURL: https://github.com/KiraPixel/lksp-infra.git
    targetRevision: HEAD
  sources: []
  project: logging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true