apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: logging-appset
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/KiraPixel/lksp-infra.git
        revision: HEAD
        directories:
          - path: manifests/logging
  template:
    metadata:
      name: '{{.path.basename}}'
    spec:
      project: logging
      source:
        repoURL: https://github.com/KiraPixel/lksp-infra.git
        targetRevision: HEAD
        path: '{{.path }}'
      destination:
        server: https://kubernetes.default.svc
        namespace: logging
      syncPolicy:
        automated:
          prune: false
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
  goTemplate: true
